### ISSUE TITLE
[UPDATE] - WoA Helper 1.7

### ISSUE THREAD

**Issue by n00b69** [woa-raphael/woa-raphael#23]
### Description

New WoA Helper version is out, so add it

https://github.com/erdilS/Port-Windows-11-Xiaomi-Pad-5/releases/download/dualboot/woahelper.apk

### Reproduction steps

```bash
No
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 On The Phone.
- [X] There is no issue already describing my problem.

**Comment by graphiks** [comment]
who did this😂
