### ISSUE TITLE
[QUESTION] - <title> Can I use it with custom ROM?

### ISSUE THREAD

**Issue by Krutifulmen** [woa-raphael/woa-raphael#26]
### Question

Can I use dual boot with custom ROM?

### Agreement

- [X] I am asking a sensible question.
- [X] I am not trying to waste time.
- [X] There is no issue already describing my problem.

**Comment by saulgoodman4534** [comment]
no, your phone will explode

**Comment by Krutifulmen** [comment]
💥💥💥💥💥💥💥💥💥💥💥💥

**Comment by Krutifulmen** [comment]
but can you actually say, can I use it with custom ROM or not, please 🙂

**Comment by saulgoodman4534** [comment]
yes

**Comment by Krutifulmen** [comment]
thank you! :3
